# -*- coding: utf-8 -*-
"""Decision_Tree_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qOKDmoVuA8_JdXMntx91X90fxe6XoOCe

Importing libraries
"""

import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

"""Load the dataset"""

data = pd.read_csv('Iris.csv')
# Check unique species count
data.Species.nunique()

"""Define features and target variable"""

features = data.drop('Species', axis=1)  # Features
target = data['Species']  # Target variable

"""Split data into training and testing sets"""

train_features, test_features, train_target, test_target = train_test_split(features, target, test_size=0.3, random_state=42)

"""Create Decision Tree classifier and train it"""

classifier = DecisionTreeClassifier()
classifier.fit(train_features, train_target)

"""Make predictions on the test set"""

predictions = classifier.predict(test_features)
model_accuracy = accuracy_score(test_target, predictions)
conf_matrix = confusion_matrix(test_target, predictions)

"""Print the results"""

print("Accuracy:", model_accuracy)
print(f'Confusion Matrix:\n,{conf_matrix}')