# -*- coding: utf-8 -*-
"""50_StartUps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XjSXJJjISJOlFmmw2NxJdVy0NRTkr3lr
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

#Reading Data
df = pd.read_csv('50_Startups.csv')
# Display basic information and box plot
df.info()
df.boxplot()
#Handling Categorical Data
df = pd.get_dummies(df, columns=['State'], drop_first=True)

from sklearn.preprocessing import MinMaxScaler

X = df.drop('Profit', axis=1)
y = df['Profit']

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

#Data Split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=0)

#Model Fitting and Pipelining

from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(X_train, y_train)

#Predicting and Evaluation
y_pred = regressor.predict(X_test)
# R2 Score
print("R2 Score:", r2_score(y_test, y_pred))
# RMSE
print("Root Mean Squared Error (RMSE):", np.sqrt(mean_squared_error(y_test, y_pred)))
# MSE
print("Mean Squared Error (MSE):", mean_squared_error(y_test, y_pred))
# MAE (Optional)
print("Mean Absolute Error (MAE):", mean_absolute_error(y_test, y_pred))